[rpcServer]
    addr = ":3109"
    timeout = "1s"

[mysql]
    addr = "127.0.0.1:3306"
    dbuser = "root"
    dbpwd = "123456"
    database = "user"
    table = "account"

[xlog]
    path = "gbiz.log"
    level = "debug"